import { ApplicationError, type ApplicationErrorCode } from "@nusashell/application";
import { ProtocolError } from "../protocol/websocket-error.js";

const ERROR_CODE_MAP: Record<ApplicationErrorCode, string> = {
  PLUGIN_NOT_FOUND: "PLUGIN_NOT_FOUND",
  PLUGIN_DISABLED: "PLUGIN_DISABLED",
  PLUGIN_NOT_RUNNING: "PLUGIN_NOT_RUNNING",
  INVALID_RUNTIME_TRANSITION: "INVALID_RUNTIME_TRANSITION",
  PLUGIN_START_FAILED: "PLUGIN_START_FAILED",
  PLUGIN_STOP_FAILED: "PLUGIN_STOP_FAILED",
  PLUGIN_CRASHED: "PLUGIN_CRASHED",
  TOOL_NOT_FOUND: "TOOL_NOT_FOUND",
  TOOL_CALL_TIMEOUT: "TOOL_CALL_TIMEOUT",
  TOOL_CALL_CANCELLED: "TOOL_CALL_CANCELLED",
  MCP_CONNECTION_FAILED: "MCP_CONNECTION_FAILED",
  OPERATION_CONFLICT: "OPERATION_CONFLICT",
  OPERATION_TIMEOUT: "OPERATION_TIMEOUT",
  AGENT_PROVIDER_NOT_FOUND: "AGENT_PROVIDER_NOT_FOUND",
  AGENT_INVALID_INPUT: "AGENT_INVALID_INPUT",
  AGENT_TOOL_NOT_ALLOWED: "AGENT_TOOL_NOT_ALLOWED",
  AGENT_MAX_TOOL_ROUNDS: "AGENT_MAX_TOOL_ROUNDS",
  AGENT_PROVIDER_FAILED: "AGENT_PROVIDER_FAILED",
  AGENT_TURN_CANCELLED: "AGENT_TURN_CANCELLED",
  UNAUTHORIZED: "UNAUTHORIZED",
  UNAVAILABLE: "UNAVAILABLE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  JOB_NOT_FOUND: "JOB_NOT_FOUND",
  JOB_INVALID_SCHEDULE: "JOB_INVALID_SCHEDULE",
  JOB_INVALID_TRIGGER: "JOB_INVALID_TRIGGER",
  JOB_NOT_RUNNING: "JOB_NOT_RUNNING",
  PIPELINE_NOT_FOUND: "PIPELINE_NOT_FOUND",
  PIPELINE_INVALID: "PIPELINE_INVALID",
  ACP_SESSION_NOT_FOUND: "ACP_SESSION_NOT_FOUND",
  ACP_PROVIDER_FAILED: "ACP_PROVIDER_FAILED",
  WORKSPACE_SYNC_FAILED: "WORKSPACE_SYNC_FAILED",
};

export function mapApplicationError(
  error: ApplicationError,
  requestId?: string,
): ProtocolError {
  const code = ERROR_CODE_MAP[error.code] ?? "INTERNAL_ERROR";
  return new ProtocolError(code, error.message, requestId, error.details);
}
