export const FILES_TOOL_NAMES = Object.freeze([
  "files_list",
  "files_tree",
  "files_read",
  "files_write",
  "files_mkdir",
  "files_move",
  "files_copy",
  "files_delete",
  "files_search",
  "files_info",
  "files_grep",
  "files_patch",
  "files_append",
]);
