// Command gen-catalog fetches model metadata from public, key-less
// sources (models.dev/api.json + openrouter.ai/api/v1/models) and
// generates a Go source file with the merged catalog embedded as a
// constant. The generated file is committed and used as a fallback
// when the live catalog fetch fails at runtime (upstream down, offline).
//
// This mirrors the mockgen/wire pattern: a build-time code generator
// produces a static artifact that ships with the binary.
//
// Usage:
//
//	go run ./cmd/gen-catalog                    # regenerate catalog_gen.go
//	go run ./cmd/gen-catalog -check             # fail if committed file is stale
//	go run ./cmd/gen-catalog -o path/to/file.go # custom output path
//	go run ./cmd/gen-catalog -repo-root /path
//
// The default output is infrastructure/config/catalog_gen.go.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

const (
	modelsDevURL    = "https://models.dev/api.json"
	openRouterURL   = "https://openrouter.ai/api/v1/models"
	defaultTimeout  = 60 * time.Second
	headerGenerated = "// Code generated by cmd/gen-catalog. DO NOT EDIT.\n"
)

func main() {
	repoRoot := flag.String("repo-root", ".", "repository root (to resolve default output path)")
	outPath := flag.String("o", "", "output file path (default: <repo-root>/infrastructure/config/catalog_gen.go)")
	check := flag.Bool("check", false, "fail if the committed file differs from generated")
	flag.Parse()

	if *outPath == "" {
		*outPath = filepath.Join(*repoRoot, "infrastructure/config", "catalog_gen.go")
	}

	ctx, cancel := context.WithTimeout(context.Background(), defaultTimeout)
	defer cancel()

	entries, err := fetchAndMerge(ctx)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-catalog: %v\n", err)
		os.Exit(1)
	}

	generated := renderGo(entries)

	if *check {
		existing, err := os.ReadFile(*outPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gen-catalog: cannot read %s: %v\n", *outPath, err)
			os.Exit(1)
		}
		if !bytes.Equal(existing, generated) {
			fmt.Fprintf(os.Stderr, "gen-catalog: %s is stale — run 'go run ./cmd/gen-catalog' to regenerate\n", *outPath)
			os.Exit(1)
		}
		fmt.Printf("gen-catalog: %s is fresh (%d entries)\n", *outPath, len(entries))
		return
	}

	if err := os.WriteFile(*outPath, generated, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-catalog: write failed: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("gen-catalog: wrote %s (%d entries)\n", *outPath, len(entries))
}

// catalogEntry is the merged, normalized metadata for one model.
// This struct is serialized to JSON in the generated Go file.
type catalogEntry struct {
	ID               string   `json:"id"`
	Name             string   `json:"name,omitempty"`
	Description      string   `json:"description,omitempty"`
	Context          int      `json:"context,omitempty"`
	Output           int      `json:"output,omitempty"`
	InputCost        float64  `json:"input_cost,omitempty"`
	OutputCost       float64  `json:"output_cost,omitempty"`
	CacheReadCost    float64  `json:"cache_read_cost,omitempty"`
	Reasoning        bool     `json:"reasoning,omitempty"`
	ToolCall         bool     `json:"tool_call,omitempty"`
	StructuredOutput bool     `json:"structured_output,omitempty"`
	Vision           bool     `json:"vision,omitempty"`
	SupportedEfforts []string `json:"supported_efforts,omitempty"`
	KnowledgeCutoff  string   `json:"knowledge_cutoff,omitempty"`
	Kind             string   `json:"kind"`
}

// fetchAndMerge downloads both catalogs, merges them (models.dev takes
// priority for overlapping fields, openrouter fills gaps), and returns
// a sorted, deduplicated entry list.
func fetchAndMerge(ctx context.Context) ([]catalogEntry, error) {
	md, err := fetchModelsDev(ctx)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-catalog: models.dev fetch failed: %v (continuing with openrouter only)\n", err)
	}
	or, err := fetchOpenRouter(ctx)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-catalog: openrouter fetch failed: %v\n", err)
	}
	if md == nil && or == nil {
		return nil, fmt.Errorf("both catalog sources failed")
	}

	merged := make(map[string]*catalogEntry)

	// models.dev first (richer capability data)
	for _, e := range md {
		merged[e.ID] = &e
	}

	// openrouter fills gaps
	for id, e := range or {
		existing, ok := merged[id]
		if !ok {
			merged[id] = &e
			continue
		}
		if existing.Context == 0 && e.Context != 0 {
			existing.Context = e.Context
		}
		if existing.InputCost == 0 && e.InputCost != 0 {
			existing.InputCost = e.InputCost
		}
		if existing.OutputCost == 0 && e.OutputCost != 0 {
			existing.OutputCost = e.OutputCost
		}
		if existing.Description == "" && e.Description != "" {
			existing.Description = e.Description
		}
		if existing.Name == "" && e.Name != "" {
			existing.Name = e.Name
		}
		if existing.Kind == "" {
			existing.Kind = e.Kind
		}
	}

	out := make([]catalogEntry, 0, len(merged))
	for _, e := range merged {
		if e.Kind == "" {
			e.Kind = "chat"
		}
		out = append(out, *e)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out, nil
}

// ---- models.dev ----

type modelsDevProvider struct {
	ID     string                    `json:"id"`
	Name   string                    `json:"name"`
	Models map[string]modelsDevModel `json:"models"`
}

type modelsDevModel struct {
	ID               string `json:"id"`
	Name             string `json:"name"`
	Description      string `json:"description"`
	Reasoning        bool   `json:"reasoning"`
	ToolCall         bool   `json:"tool_call"`
	StructuredOutput bool   `json:"structured_output"`
	Temperature      bool   `json:"temperature"`
	Attachment       bool   `json:"attachment"`
	Knowledge        string `json:"knowledge"`
	ReasoningOptions []struct {
		Type   string   `json:"type"`
		Values []string `json:"values"`
	} `json:"reasoning_options"`
	Modalities struct {
		Input  []string `json:"input"`
		Output []string `json:"output"`
	} `json:"modalities"`
	Limit struct {
		Context int `json:"context"`
		Output  int `json:"output"`
	} `json:"limit"`
	Cost struct {
		Input     float64 `json:"input"`
		Output    float64 `json:"output"`
		CacheRead float64 `json:"cache_read"`
	} `json:"cost"`
}

func fetchModelsDev(ctx context.Context) ([]catalogEntry, error) {
	body, err := fetchJSON(ctx, modelsDevURL)
	if err != nil {
		return nil, err
	}
	var providers map[string]modelsDevProvider
	if err := json.Unmarshal(body, &providers); err != nil {
		return nil, fmt.Errorf("models.dev parse: %w", err)
	}
	var out []catalogEntry
	for _, prov := range providers {
		for modelKey, m := range prov.Models {
			e := catalogEntry{
				ID:               modelKey,
				Name:             m.Name,
				Description:      m.Description,
				Context:          m.Limit.Context,
				Output:           m.Limit.Output,
				InputCost:        m.Cost.Input,
				OutputCost:       m.Cost.Output,
				CacheReadCost:    m.Cost.CacheRead,
				Reasoning:        m.Reasoning,
				ToolCall:         m.ToolCall,
				StructuredOutput: m.StructuredOutput,
				KnowledgeCutoff:  m.Knowledge,
				Kind:             detectKind(modelKey, m),
			}
			for _, in := range m.Modalities.Input {
				if in == "image" {
					e.Vision = true
				}
			}
			if m.Attachment {
				e.Vision = true
			}
			for _, opt := range m.ReasoningOptions {
				if opt.Type == "effort" {
					e.SupportedEfforts = append(e.SupportedEfforts, opt.Values...)
				}
			}
			out = append(out, e)
		}
	}
	return out, nil
}

// detectKind mirrors modelcatalog.detectKind for the generator.
func detectKind(id string, m modelsDevModel) string {
	lowerID := strings.ToLower(id)
	lowerName := strings.ToLower(m.Name)
	lowerDesc := strings.ToLower(m.Description)

	embPatterns := []string{
		"embed", "embedding", "bge-", "e5-", "gte-", "jina-embed",
		"nomic-embed", "voyage-", "text-embedding", "nv-embed",
		"nemoretriever", "embedcode",
	}
	for _, p := range embPatterns {
		if strings.Contains(lowerID, p) || strings.Contains(lowerName, p) {
			return "embedding"
		}
	}
	if strings.Contains(lowerDesc, "embedding model") {
		return "embedding"
	}

	out := m.Modalities.Output
	in := m.Modalities.Input
	hasImageOut := containsStr(out, "image")
	hasVideoOut := containsStr(out, "video")
	hasAudioOut := containsStr(out, "audio")
	hasTextOut := containsStr(out, "text")

	switch {
	case hasVideoOut:
		return "video"
	case hasImageOut && !hasTextOut:
		return "image"
	case hasAudioOut && !hasTextOut:
		return "tts"
	}

	hasAudioIn := containsStr(in, "audio")
	hasImageIn := containsStr(in, "image")
	if hasAudioIn && hasTextOut && !hasImageIn {
		return "stt"
	}
	return "chat"
}

func containsStr(s []string, v string) bool {
	for _, x := range s {
		if x == v {
			return true
		}
	}
	return false
}

// ---- openrouter ----

type openRouterResponse struct {
	Data []struct {
		ID            string `json:"id"`
		Name          string `json:"name"`
		Description   string `json:"description"`
		ContextLength int    `json:"context_length"`
		Knowledge     string `json:"knowledge_cutoff"`
		Pricing       struct {
			Prompt     string `json:"prompt"`
			Completion string `json:"completion"`
		} `json:"pricing"`
		Architecture struct {
			InputModalities  []string `json:"input_modalities"`
			OutputModalities []string `json:"output_modalities"`
		} `json:"architecture"`
		SupportedParameters []string        `json:"supported_parameters"`
		Reasoning           json.RawMessage `json:"reasoning"`
	} `json:"data"`
}

func fetchOpenRouter(ctx context.Context) (map[string]catalogEntry, error) {
	body, err := fetchJSON(ctx, openRouterURL)
	if err != nil {
		return nil, err
	}
	var resp openRouterResponse
	if err := json.Unmarshal(body, &resp); err != nil {
		return nil, fmt.Errorf("openrouter parse: %w", err)
	}
	out := make(map[string]catalogEntry, len(resp.Data))
	for _, m := range resp.Data {
		if m.ID == "" {
			continue
		}
		e := catalogEntry{
			ID:          m.ID,
			Name:        m.Name,
			Description: m.Description,
			Context:     m.ContextLength,
		}
		if v, err := parseFloat(m.Pricing.Prompt); err == nil {
			e.InputCost = v * 1_000_000
		}
		if v, err := parseFloat(m.Pricing.Completion); err == nil {
			e.OutputCost = v * 1_000_000
		}
		for _, p := range m.SupportedParameters {
			switch p {
			case "tools", "tool_choice":
				e.ToolCall = true
			case "response_format", "structured_outputs":
				e.StructuredOutput = true
			case "reasoning", "include_reasoning", "reasoning_effort":
				e.Reasoning = true
			}
		}
		for _, im := range m.Architecture.InputModalities {
			if im == "image" {
				e.Vision = true
			}
		}
		// Kind from openrouter modality
		outMods := m.Architecture.OutputModalities
		switch {
		case containsStr(outMods, "video"):
			e.Kind = "video"
		case containsStr(outMods, "image") && !containsStr(outMods, "text"):
			e.Kind = "image"
		case containsStr(outMods, "audio") && !containsStr(outMods, "text"):
			e.Kind = "tts"
		default:
			if isEmbeddingByName(m.ID) {
				e.Kind = "embedding"
			} else {
				e.Kind = "chat"
			}
		}
		out[m.ID] = e
	}
	return out, nil
}

func isEmbeddingByName(id string) bool {
	lower := strings.ToLower(id)
	for _, p := range []string{"embed", "bge-", "e5-", "gte-", "voyage-", "text-embedding"} {
		if strings.Contains(lower, p) {
			return true
		}
	}
	return false
}

// ---- helpers ----

func fetchJSON(ctx context.Context, url string) ([]byte, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", "application/json")
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s returned %d", url, resp.StatusCode)
	}
	return io.ReadAll(resp.Body)
}

func parseFloat(s string) (float64, error) {
	var f float64
	_, err := fmt.Sscanf(s, "%f", &f)
	return f, err
}

// renderGo produces the Go source file with the catalog embedded as JSON.
// Uses a double-quoted Go string with proper escaping (not backtick raw
// string) because model descriptions can contain backticks.
func renderGo(entries []catalogEntry) []byte {
	data, err := json.Marshal(entries)
	if err != nil {
		panic(err)
	}
	var buf bytes.Buffer
	buf.WriteString(headerGenerated)
	buf.WriteString("\n")
	buf.WriteString("package config\n\n")
	buf.WriteString("// catalog_gen.go is generated by cmd/gen-catalog from\n")
	buf.WriteString("// models.dev/api.json + openrouter.ai/api/v1/models.\n")
	buf.WriteString("// It provides a fallback catalog used by the modelcatalog\n")
	buf.WriteString("// package when the live fetch fails (upstream down, offline).\n")
	buf.WriteString("//\n")
	buf.WriteString("// Do not edit this file directly — run 'go run ./cmd/gen-catalog'.\n\n")
	buf.WriteString("// EmbeddedCatalogJSON is the merged, normalized model catalog\n")
	buf.WriteString("// from models.dev + openrouter, captured at generation time.\n")
	buf.WriteString("// It is a JSON array; parse with encoding/json.\n\n")
	fmt.Fprintf(&buf, "const EmbeddedCatalogJSON = %q\n", string(data))
	return buf.Bytes()
}
