export type {
  PluginRepositoryPort,
  PluginInstallerPort,
  PluginProcessPort,
  ProcessHandle,
  McpClientPort,
  McpClientFactoryPort,
  ToolDescriptor,
  PromptArgumentDescriptor,
  PromptDescriptor,
  PromptResult,
  ResourceDescriptor,
  ResourceReadResult,
  ResourceTemplateDescriptor,
  CompletionReference,
  CompletionResult,
  RootDescriptor,
  ClockPort,
  LoggerPort,
  AutomationClientDeps,
  AutomationRateLimiterPort,
} from "./ports/index.js";
export {
  PluginOperationQueue,
  PluginRuntimeManager,
  type PluginRuntimeManagerDeps,
  type PluginView,
  type StartPluginOptions,
  type CallToolOptions,
  type WorkspaceSyncResult,
  type PluginLaunchSpec,
  resolveIcon,
  hasPluginUi,
  AutomationEmitRegistry,
} from "./services/index.js";
export type {
  StartPluginCommand,
  StartPluginResult,
  StopPluginCommand,
  StopPluginResult,
  RestartPluginCommand,
  RestartPluginResult,
  InstallPluginCommand,
  InstallPluginResult,
  UninstallPluginCommand,
  UninstallPluginResult,
  SetPluginAutostartCommand,
} from "./commands/index.js";
export {
  StartPluginHandler,
  StopPluginHandler,
  RestartPluginHandler,
  InstallPluginHandler,
  UninstallPluginHandler,
  SetPluginAutostartHandler,
} from "./commands/index.js";
export type {
  ListPluginsQuery,
  ListPluginsResult,
  PluginListItem,
  GetPluginQuery,
  GetPluginResult,
  GetPluginStateQuery,
  GetPluginStateResult,
} from "./queries/index.js";
export { ListPluginsHandler, GetPluginHandler, GetPluginStateHandler } from "./queries/index.js";
